services:
  redis:
        image: redis:latest
        container_name: redis_cache
        ports:
          - "6379:6379"  # Redis default port
        networks:
          - redis_net

  inupco.sho:
    image: ${DOCKER_REGISTRY-}inupcosho
    build:
      context: .
      dockerfile: iNUPCO.SHO/Dockerfile

    networks:
        - iNUPCO_SHO
        - redis_net
    environment:
      RABBITMQ__HostName: rabbitmq  # RabbitMQ container hostname
      RABBITMQ__UserName: guest  # Default RabbitMQ username
      RABBITMQ__Password: guest  # Default RabbitMQ password

      
networks:
  iNUPCO_SHO:
    name: rabbitmq_go_net
    external: true
  redis_net:
    driver: bridge  


